// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjRUnbjA5FZIeeeVtDguNItO1IzX9g9r0',
    appId: '1:189210323480:web:4673b326060020cbf4316d',
    messagingSenderId: '189210323480',
    projectId: 'spch-ff9e3',
    authDomain: 'spch-ff9e3.firebaseapp.com',
    databaseURL: 'https://spch-ff9e3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spch-ff9e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjDK3uPrv5Js5ZXyqZ__skdKmKENByC54',
    appId: '1:189210323480:android:56153cb49787d66cf4316d',
    messagingSenderId: '189210323480',
    projectId: 'spch-ff9e3',
    databaseURL: 'https://spch-ff9e3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spch-ff9e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL6lWNdkSuvm7EwhYZyQ3fwYT5WSok8Fs',
    appId: '1:189210323480:ios:ec91e72404c11669f4316d',
    messagingSenderId: '189210323480',
    projectId: 'spch-ff9e3',
    databaseURL: 'https://spch-ff9e3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spch-ff9e3.appspot.com',
    iosBundleId: 'com.example.csvpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL6lWNdkSuvm7EwhYZyQ3fwYT5WSok8Fs',
    appId: '1:189210323480:ios:ec91e72404c11669f4316d',
    messagingSenderId: '189210323480',
    projectId: 'spch-ff9e3',
    databaseURL: 'https://spch-ff9e3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spch-ff9e3.appspot.com',
    iosBundleId: 'com.example.csvpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjRUnbjA5FZIeeeVtDguNItO1IzX9g9r0',
    appId: '1:189210323480:web:d6261e878dccff71f4316d',
    messagingSenderId: '189210323480',
    projectId: 'spch-ff9e3',
    authDomain: 'spch-ff9e3.firebaseapp.com',
    databaseURL: 'https://spch-ff9e3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spch-ff9e3.appspot.com',
  );
}
