// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVPiYlZxRxtzneYuSvYcCn-QDsWDlK8-8',
    appId: '1:89262715667:web:84c1a959882a47acca60e6',
    messagingSenderId: '89262715667',
    projectId: 'voice-app-37476',
    authDomain: 'voice-app-37476.firebaseapp.com',
    databaseURL: 'https://voice-app-37476-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'voice-app-37476.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR57iw4_SWNy67Fr7J4JVteowrZjhjul4',
    appId: '1:89262715667:android:d617acecdc933e28ca60e6',
    messagingSenderId: '89262715667',
    projectId: 'voice-app-37476',
    databaseURL: 'https://voice-app-37476-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'voice-app-37476.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdQzSb-itvNuDax_DSpQwpx4dWt99eef4',
    appId: '1:89262715667:ios:1a39823713cd67cdca60e6',
    messagingSenderId: '89262715667',
    projectId: 'voice-app-37476',
    databaseURL: 'https://voice-app-37476-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'voice-app-37476.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdQzSb-itvNuDax_DSpQwpx4dWt99eef4',
    appId: '1:89262715667:ios:1a39823713cd67cdca60e6',
    messagingSenderId: '89262715667',
    projectId: 'voice-app-37476',
    databaseURL: 'https://voice-app-37476-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'voice-app-37476.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVPiYlZxRxtzneYuSvYcCn-QDsWDlK8-8',
    appId: '1:89262715667:web:3a9214d94b1258f4ca60e6',
    messagingSenderId: '89262715667',
    projectId: 'voice-app-37476',
    authDomain: 'voice-app-37476.firebaseapp.com',
    databaseURL: 'https://voice-app-37476-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'voice-app-37476.appspot.com',
  );

}